version: '3'

services:
  php:
    image: php:7.1-apache
    links:
      - db
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
    restart: on-failure
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=very-secure
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "90:80"
      - "9090:8080"
    links:
      - db
  composer:
    image: composer
    user: "1000"
    volumes:
      - ./public:/app

volumes:
  db: