version: '3'

services:
  php:
    build: php-apache/
    links:
      - db
    ports:
      - "80:80"
    volumes:
      - /srv/www/typo3:/var/www/html
    restart: on-failure
  db:
    image: mariadb:10.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=very-secure
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "90:80"
      - "9090:8080"
    links:
      - db

  composer:
    image: composer
    volumes:
      - /srv/www/typo3:/app
  phpunit:
    image: phpunit/phpunit
    user: "1000"
    volumes:
      - /srv/www/typo3:/app

volumes:
  db: