version: '3'

services:
  php:
    image: webdevops/php-nginx-dev:7.1
    links:
      - db
    ports:
      - "80:80"
    volumes:
      - ./public:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/web
    restart: on-failure
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=very-secure
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "90:80"
      - "9090:8080"
    links:
      - db

  composer:
    image: composer
    user: "1000"
    volumes:
      - ./public:/app
  phpunit:
    image: phpunit/phpunit
    user: "1000"
    volumes:
      - ./public:/app

volumes:
  db: